export const projects = [
  {
    id: 1,
    project: "Portal Web",
    tickets: [
      {
        id: 1,
        title: "Error al iniciar sesión con Google",
        description: "...",
        category: "bug",
        priority: "high",
        status: "open",
        assignedTo: "Ana Torres",
        createdAt: "2026-01-10T09:15:00Z",
        comments: [
          {
            author: "Luis Pérez",
            text: "Reproduzco el error en Firefox.",
            createdAt: "2026-01-10T10:00:00Z",
          },
          {
            author: "Ana Torres",
            text: "Revisaré el login de Google hoy.",
            createdAt: "2026-01-10T10:15:00Z",
          },
        ],
      },
      {
        id: 2,
        title: "Agregar autenticación de dos factores",
        description: "...",
        category: "feature",
        priority: "medium",
        status: "in_progress",
        assignedTo: "Luis Pérez",
        createdAt: "2026-01-08T14:30:00Z",
        comments: [],
      },
      {
        id: 3,
        title: "Validación de correo electrónico",
        description: "...",
        category: "task",
        priority: "low",
        status: "open",
        assignedTo: "Laura Fernández",
        createdAt: "2026-01-07T10:20:00Z",
        comments: [],
      },
      {
        id: 4,
        title: "Optimizar carga de la página de inicio",
        description: "...",
        category: "task",
        priority: "medium",
        status: "in_progress",
        assignedTo: "Carlos Ramírez",
        createdAt: "2026-01-05T15:10:00Z",
        comments: [],
      },
      {
        id: 5,
        title: "Actualizar librerías de frontend",
        description: "...",
        category: "task",
        priority: "medium",
        status: "open",
        assignedTo: "Sofía Martínez",
        createdAt: "2026-01-06T11:00:00Z",
        comments: [],
      },
      // Nuevos tickets añadidos
      {
        id: 21,
        title: "Error de responsive en la página de contacto",
        description: "El footer se desborda en móviles.",
        category: "bug",
        priority: "medium",
        status: "open",
        assignedTo: "Laura Fernández",
        createdAt: "2026-01-11T09:00:00Z",
        comments: [],
      },
      {
        id: 22,
        title: "Integrar chat en tiempo real",
        description: "Implementar chat con WebSockets",
        category: "feature",
        priority: "high",
        status: "in_progress",
        assignedTo: "Carlos Ramírez",
        createdAt: "2026-01-11T12:00:00Z",
        comments: [],
      },
    ],
  },
  {
    id: 2,
    project: "Dashboard Admin",
    tickets: [
      {
        id: 6,
        title: "Reporte de ventas mensual no carga",
        description: "...",
        category: "bug",
        priority: "high",
        status: "in_progress",
        assignedTo: "Marta Gómez",
        createdAt: "2026-01-09T16:45:00Z",
        comments: [],
      },
      {
        id: 7,
        title: "Agregar filtros avanzados en el dashboard",
        description: "...",
        category: "feature",
        priority: "low",
        status: "open",
        assignedTo: "Diego López",
        createdAt: "2026-01-06T10:10:00Z",
        comments: [],
      },
      {
        id: 8,
        title: "Error en exportación de CSV",
        description: "...",
        category: "bug",
        priority: "medium",
        status: "open",
        assignedTo: "Laura Fernández",
        createdAt: "2026-01-04T13:25:00Z",
        comments: [],
      },
      {
        id: 9,
        title: "Agregar autenticación de usuario para admins",
        description: "...",
        category: "feature",
        priority: "high",
        status: "in_progress",
        assignedTo: "Carlos Ramírez",
        createdAt: "2026-01-03T09:50:00Z",
        comments: [],
      },
      {
        id: 10,
        title: "Actualizar estilos del dashboard",
        description: "...",
        category: "task",
        priority: "low",
        status: "open",
        assignedTo: "Ana Torres",
        createdAt: "2026-01-02T12:15:00Z",
        comments: [],
      },
      // Nuevos tickets
      {
        id: 23,
        title: "Agregar dashboard de métricas de usuarios",
        description: "Nuevo módulo para mostrar métricas activas.",
        category: "feature",
        priority: "medium",
        status: "open",
        assignedTo: "Diego López",
        createdAt: "2026-01-11T11:00:00Z",
        comments: [],
      },
      {
        id: 24,
        title: "Error al filtrar por fechas",
        description:
          "Al aplicar filtro de rango de fechas, no se muestran resultados.",
        category: "bug",
        priority: "high",
        status: "in_progress",
        assignedTo: "Marta Gómez",
        createdAt: "2026-01-11T09:30:00Z",
        comments: [],
      },
    ],
  },
  {
    id: 3,
    project: "App Móvil",
    tickets: [
      {
        id: 11,
        title: "Crash al abrir perfil de usuario",
        description: "...",
        category: "bug",
        priority: "high",
        status: "open",
        assignedTo: "Sofía Martínez",
        createdAt: "2026-01-05T09:50:00Z",
        comments: [],
      },
      {
        id: 12,
        title: "Notificaciones push para promociones",
        description: "...",
        category: "feature",
        priority: "medium",
        status: "in_progress",
        assignedTo: "Diego López",
        createdAt: "2026-01-04T14:00:00Z",
        comments: [],
      },
      {
        id: 13,
        title: "Error de ubicación GPS",
        description: "...",
        category: "bug",
        priority: "medium",
        status: "in_progress",
        assignedTo: "Laura Fernández",
        createdAt: "2026-01-03T10:30:00Z",
        comments: [],
      },
      {
        id: 14,
        title: "Actualizar SDK de pagos",
        description: "...",
        category: "task",
        priority: "medium",
        status: "open",
        assignedTo: "Carlos Ramírez",
        createdAt: "2026-01-02T15:20:00Z",
        comments: [],
      },
      {
        id: 15,
        title: "Mejorar animaciones de carga",
        description: "...",
        category: "task",
        priority: "low",
        status: "open",
        assignedTo: "Ana Torres",
        createdAt: "2026-01-01T09:00:00Z",
        comments: [],
      },
      // Nuevos tickets
      {
        id: 25,
        title: "Error en notificaciones push",
        description: "No llegan notificaciones a algunos usuarios.",
        category: "bug",
        priority: "high",
        status: "in_progress",
        assignedTo: "Diego López",
        createdAt: "2026-01-11T08:45:00Z",
        comments: [],
      },
      {
        id: 26,
        title: "Agregar integración con Google Analytics",
        description: "Monitorear uso de la app en tiempo real.",
        category: "feature",
        priority: "medium",
        status: "open",
        assignedTo: "Sofía Martínez",
        createdAt: "2026-01-11T10:00:00Z",
        comments: [],
      },
    ],
  },
  {
    id: 4,
    project: "API Backend",
    tickets: [
      {
        id: 16,
        title: "Endpoint /users devuelve 500",
        description: "...",
        category: "bug",
        priority: "high",
        status: "in_progress",
        assignedTo: "Luis Pérez",
        createdAt: "2026-01-09T11:10:00Z",
        comments: [],
      },
      {
        id: 17,
        title: "Agregar logging avanzado",
        description: "...",
        category: "feature",
        priority: "medium",
        status: "open",
        assignedTo: "Sofía Martínez",
        createdAt: "2026-01-08T14:50:00Z",
        comments: [],
      },
      {
        id: 18,
        title: "Actualizar documentación Swagger",
        description: "...",
        category: "task",
        priority: "low",
        status: "open",
        assignedTo: "Diego López",
        createdAt: "2026-01-07T13:40:00Z",
        comments: [],
      },
      {
        id: 19,
        title: "Implementar paginación en /tickets",
        description: "...",
        category: "feature",
        priority: "medium",
        status: "in_progress",
        assignedTo: "Carlos Ramírez",
        createdAt: "2026-01-06T10:30:00Z",
        comments: [],
      },
      {
        id: 20,
        title: "Corregir bug de autenticación JWT",
        description: "...",
        category: "bug",
        priority: "high",
        status: "open",
        assignedTo: "Ana Torres",
        createdAt: "2026-01-05T09:00:00Z",
        comments: [],
      },
      // Nuevos tickets
      {
        id: 27,
        title: "Error al crear usuario con roles",
        description: "La API devuelve 400 al asignar roles múltiples.",
        category: "bug",
        priority: "high",
        status: "in_progress",
        assignedTo: "Luis Pérez",
        createdAt: "2026-01-11T09:20:00Z",
        comments: [],
      },
      {
        id: 28,
        title: "Agregar endpoint para estadísticas",
        description: "Nuevo endpoint GET /stats para reportes.",
        category: "feature",
        priority: "medium",
        status: "open",
        assignedTo: "Sofía Martínez",
        createdAt: "2026-01-11T11:10:00Z",
        comments: [],
      },
    ],
  },
];
